# NumPy Medium Skills

Welcome to the NumPy Medium Skills tutorial! In this notebook, we will build on the fundamental concepts of NumPy covered in the basics tutorial. We will explore more advanced array operations, mathematical functions, and array manipulation techniques. These skills are essential for tackling more complex data science tasks.

## Broadcasting

Broadcasting is a powerful mechanism that allows NumPy to work with arrays of different shapes during arithmetic operations. It simplifies the code and increases efficiency.

**Intuition and Use-Cases:**
Broadcasting is particularly useful when you need to perform operations on arrays of different sizes without explicitly replicating data. This is common in image processing, where you might need to apply a filter to an entire image without increasing memory usage.

In [1]:
import numpy as np

# Example of broadcasting
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[10], [20]])

print("Array a:\n", a)
print("Array b:\n", b)

# Broadcasting b to match the shape of a
result = a + b
print("Broadcasting result:\n", result)

Array a:
 [[1 2 3]
 [4 5 6]]
Array b:
 [[10]
 [20]]
Broadcasting result:
 [[11 12 13]
 [24 25 26]]


### Explanation of Broadcasting

In the example above, array `b` is broadcasted to match the shape of array `a`. This means that `b` is virtually expanded to:

```
b = [[10, 10, 10],
     [20, 20, 20]]
```

This allows the element-wise addition to be performed between `a` and the broadcasted `b`.

## Universal Functions (ufuncs)

Universal Functions, or ufuncs, are functions that operate element-wise on arrays. They provide a fast and vectorized operation on NumPy arrays.

**Intuition and Use-Cases:**
Ufuncs are essential for efficient numerical computations. They are used extensively in scientific computing, data analysis, and machine learning for operations like element-wise addition, multiplication, and trigonometric functions.

In [2]:
# Example of ufunc
a = np.array([[1, 2, 3], [4, 5, 6]])

print("Element-wise square root:\n", np.sqrt(a))

Element-wise square root:
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


### Explanation of Ufuncs

In the example above, `np.sqrt` is a ufunc that computes the square root of each element in the array `a`. This operation is performed element-wise, meaning that each element in the array is processed individually.

## Advanced Indexing

Advanced indexing allows for more complex and flexible selection of elements from an array. It can be done using integer arrays or Boolean arrays.

**Intuition and Use-Cases:**
Advanced indexing is useful when you need to select non-contiguous or specific elements from an array. This is common in data preprocessing, where you might need to filter out specific data points based on certain criteria.

In [3]:
# Example of advanced indexing
a = np.array([[1, 2, 3], [4, 5, 6]])

# Selecting elements at positions (0,1) and (1,2)
selected_elements = a[(0, 1), (1, 2)]
print("Selected elements:\n", selected_elements)

Selected elements:
 [2 6]


### Explanation of Advanced Indexing

In the example above, we use a tuple of indices to select specific elements from the array `a`. The tuple `(0, 1)` specifies the rows, and `(1, 2)` specifies the columns. This allows us to select the elements at positions `(0,1)` and `(1,2)`.

## Common Mistakes and How to Avoid Them

1. **Broadcasting Errors**: Ensure that the shapes of the arrays are compatible for broadcasting. If not, reshape the arrays appropriately.
2. **Indexing Errors**: Be careful with indexing. Python uses 0-based indexing, and negative indices can be used to access elements from the end of the array.
3. **Data Type Errors**: Ensure that all elements in a NumPy array are of the same type. Mixing types can lead to errors.
4. **Performance Pitfalls**: Avoid using Python loops for operations on NumPy arrays. Instead, use vectorized operations provided by NumPy for better performance.

## Conclusion

This concludes the NumPy Medium Skills tutorial. By now, you should have a good understanding of more advanced NumPy concepts such as broadcasting, universal functions, and advanced indexing. These skills will help you tackle more complex data science tasks efficiently.