# NumPy Basics

Welcome to the NumPy Basics tutorial! In this notebook, we will cover the fundamental concepts of NumPy, including array operations, basic mathematical functions, and array manipulation. We will also explore how these concepts can be applied to various data science tasks.

## Creating Arrays

NumPy's main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. To create a NumPy array, you can use the `array` function.

**Intuition and Use-Cases:**
Creating arrays is fundamental in NumPy as it allows you to store and manipulate large datasets efficiently. This is particularly useful in data analysis, scientific computing, and machine learning where you often deal with large matrices and vectors.

In [1]:
import numpy as np

# Creating a 1-D array
a = np.array([1, 2, 3])
print("1-D Array:", a)

# Creating a 2-D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print("2-D Array:\n", b)

1-D Array: [1 2 3]
2-D Array:
 [[1 2 3]
 [4 5 6]]


## Array Attributes

NumPy arrays have several important attributes that provide information about the array's shape, size, and data type.

**Intuition and Use-Cases:**
Understanding array attributes is crucial for effective data manipulation. Knowing the shape and dimensions of an array helps in reshaping and slicing the data appropriately. The data type attribute ensures that the operations are performed on the correct type of data, which is essential for numerical computations.

In [2]:
# Shape of the array
print("Shape of a:", a.shape)
print("Shape of b:", b.shape)

# Number of dimensions
print("Number of dimensions of a:", a.ndim)
print("Number of dimensions of b:", b.ndim)

# Data type of the elements in the array
print("Data type of a:", a.dtype)
print("Data type of b:", b.dtype)

Shape of a: (3,)
Shape of b: (2, 3)
Number of dimensions of a: 1
Number of dimensions of b: 2
Data type of a: int64
Data type of b: int64


## Array Operations

NumPy allows you to perform element-wise operations on arrays. This means that operations are applied to each element in the array individually.

**Intuition and Use-Cases:**
Element-wise operations are fundamental in numerical computations. They allow for efficient processing of large datasets, which is common in tasks such as image processing, signal processing, and machine learning model training.

In [3]:
# Element-wise addition
c = a + a
print("Element-wise addition:", c)

# Element-wise multiplication
d = a * a
print("Element-wise multiplication:", d)

# Matrix multiplication
e = np.dot(b, b.T)
print("Matrix multiplication:\n", e)

Element-wise addition: [2 4 6]
Element-wise multiplication: [1 4 9]
Matrix multiplication:
 [[14 32]
 [32 77]]


## Mathematical Functions

NumPy provides a large library of mathematical functions that can be applied to arrays. These functions operate element-wise on the array.

**Intuition and Use-Cases:**
Mathematical functions in NumPy are essential for performing complex computations efficiently. They are widely used in scientific simulations, data preprocessing, and feature engineering in machine learning.

In [ ]:
# Applying mathematical functions
f = np.sin(a)
print("Sine of each element in a:", f)

g = np.exp(a)
print("Exponential of each element in a:", g)

h = np.sqrt(a)
print("Square root of each element in a:", h)

## Array Manipulation

NumPy provides various functions to manipulate arrays, such as reshaping, stacking, and splitting arrays.

**Intuition and Use-Cases:**
Array manipulation is crucial for preparing data for various algorithms and models. Reshaping arrays allows for compatibility with different functions and models. Stacking and splitting arrays are useful for combining datasets or dividing them into manageable chunks for processing.

In [ ]:
# Reshaping an array
i = a.reshape(3, 1)
print("Reshaped array:\n", i)

# Stacking arrays
j = np.vstack((a, a))
print("Vertical stack:\n", j)

k = np.hstack((a, a))
print("Horizontal stack:", k)

# Splitting arrays
l = np.split(k, 3)
print("Split array:", l)

## NumPy Array vs Python Array

NumPy arrays are different from Python arrays in several ways:

1. **Data Type**: NumPy arrays are homogeneous, meaning all elements in the array must be of the same type. Python lists can contain elements of different types.
2. **Performance**: NumPy arrays are more efficient in terms of both speed and memory usage. This is because NumPy arrays are implemented in C, which allows for faster computations.
3. **Functionality**: NumPy provides a vast library of mathematical functions and operations that are optimized for use with NumPy arrays. Python lists lack these built-in functionalities.
4. **Multidimensional Support**: NumPy arrays can be multidimensional, while Python lists are inherently one-dimensional. However, you can create a list of lists to simulate multidimensionality in Python lists.

**Intuition and Use-Cases:**
Understanding the differences between NumPy arrays and Python lists helps in choosing the right tool for the job. For numerical computations and large-scale data manipulation, NumPy arrays are the preferred choice due to their efficiency and extensive functionality.

## Conclusion

This concludes the NumPy Basics tutorial. By now, you should have a good understanding of how to create and manipulate arrays using NumPy, as well as how to apply mathematical functions to arrays. These skills are essential for anyone working with numerical data in Python.